<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>duongtran.example</groupId>
    <artifactId>Vctrl</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <!-- SLF4J API -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.9</version>
        </dependency>

        <!-- Logback implementation -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.4.11</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/javacc/javacc -->
        <dependency>
            <groupId>javacc</groupId>
            <artifactId>javacc</artifactId>
            <version>4.1</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.12.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.17.0</version>
            <scope>test</scope>
        </dependency>


    </dependencies>


    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>javacc-maven-plugin</artifactId>
                <version>2.6</version>

                <executions>
                    <execution>
                        <id>javacc</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>javacc</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>
                    <!-- Where .jjt files live -->
<!--                    <sourceDirectory>${project.basedir}/src/main/javacc</sourceDirectory>-->

                    <!-- Generated Java output -->
<!--                    <outputDirectory>-->
<!--                        ${project.build.directory}/generated-sources/javacc-->
<!--                    </outputDirectory>-->

                    <!-- Optional but useful -->
                    <lookAhead>1</lookAhead>
                    <choiceAmbiguityCheck>2</choiceAmbiguityCheck>
                    <forceLaCheck>false</forceLaCheck>
                </configuration>

            </plugin>
        </plugins>
    </build>


</project>