options {
    STATIC = false;
    MULTI = true;
    VISITOR = true;
    NODE_DEFAULT_VOID = true;
    JDK_VERSION = "1.11";
    JAVA_UNICODE_ESCAPE = false;

    OUTPUT_DIRECTORY = "src/main/java/duongtran/vctrl/cli/parser";
    JJTREE_OUTPUT_DIRECTORY = "src/main/java/duongtran/vctrl/cli/parser";
}

PARSER_BEGIN(VctrlParser)
package duongtran.vctrl.cli.parser;

@SuppressWarnings("all")
public class VctrlParser {
}
PARSER_END(VctrlParser)

/* ====== SKIP ====== */
SKIP :
{
    " " | "\t" | "\n" | "\r"
}

/* ====== TOKENS ====== */
TOKEN :
{
      <K_INIT: "init">
    | <K_STATUS: "status">
    | <K_ADD: "add">
    | <K_COMMIT: "commit">
    | <K_LOG: "log">
    | <K_BRANCH: "branch">
    | <K_CHECKOUT: "checkout">
    | <K_MERGE: "merge">
    | <K_M: "-m"> // commit message
    | <K_D: "-d"> // remove branch
    | <K_B: "-b"> // create new branch

    | <ONELINE: "--oneline">
    | <PRETTY: "--pretty">
    | <FORMAT: "--format">

    | <EQUAL: "=">
}

/* Path / identifier */
TOKEN :
{
    <STRING_LITERAL: "\"" (~["\""])* "\"">
    | <PATH: (~[" ", "\t", "\n", "\r"])+ >
    | <FORMAT_STR: "\"" (~["\""])* "\"" | (~[" ", "\t", "\n", "\r"])+ >
}

/* ====== ENTRY ====== */
ASTCommand command() #Command:
{}
{
    (
        init_cmd()
      | add_cmd()
      | commit_cmd()
      | status_cmd()
      | branch_cmd()
      | checkout_cmd()
      | log_cmd()
    )
    {
        return jjtThis;
    }
}
/* ====== COMMANDS ====== */

void init_cmd() #InitCommand :
{
    Token path = null;
}
{
    <K_INIT>
    ( path = <PATH> )?
    {
        if (path != null) {
            jjtThis.jjtSetValue(path.image);
        }
    }
}

void add_cmd() #AddCommand :
{
    Token path;
}
{
    <K_ADD>
    path = <PATH>
    {
        jjtThis.jjtSetValue(path.image);
    }
}

void commit_cmd() #CommitCommand :
{
    Token msg;
}
{
    <K_COMMIT>
    <K_M>
    msg = <STRING_LITERAL>
    {
        String m = msg.image;
        if (m.startsWith("\"") && m.endsWith("\"")) {
            m = m.substring(1, m.length() - 1);
        }
        jjtThis.jjtSetValue(m);
    }
}

void status_cmd() #StatusCommand :
{}
{
    <K_STATUS>
}

void branch_cmd() #BranchCommand :
{
    Token name = null; // branch's name
    boolean delete = false;
}
{
    <K_BRANCH>
    (
        <K_D> {delete = true;} name = <PATH>
        | name = <PATH>
    )?
    {
        BranchCommandData data = new BranchCommandData();
        data.name = name != null ? name.image : null;
        data.delete = delete;
        jjtThis.jjtSetValue(data);
    }
}

void checkout_cmd() #CheckoutCommand :
{
    Token name = null; // branch name
    boolean create = false;
}
{
    <K_CHECKOUT>
    (
        <K_B> {create = true;} name = <PATH>
        | name = <PATH>
    )?
    {
        CheckoutCommandData data = new CheckoutCommandData();
        data.name = name.image;
        data.create = create;
        jjtThis.jjtSetValue(data);
    }
}

void log_cmd() #LogCommand :
{
    Token opt = null;
    Token fmt = null;
}
{
    <K_LOG>
    (
        <ONELINE>
      | ( (<PRETTY> | <FORMAT>) <EQUAL> fmt=<FORMAT_STR> )
    )?
    {
        LogCommandData data = new LogCommandData();

        if (opt != null && opt.image.equals("--oneline")) {
            data.oneline = true;
        }

        data.format = null;
        if (fmt != null) {
            String m = fmt.image;
            if (m.startsWith("\"") && m.endsWith("\"")) {
                m = m.substring(1, m.length() - 1);
            }
            data.format = m;
        }

        jjtThis.jjtSetValue(data);
    }
}



