/* Generated By:JJTree: Do not edit this line. ASTAddCommand.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package duongtran.vctrl.cli.parser;

public
class ASTAddCommand extends SimpleNode {
  public ASTAddCommand(int id) {
    super(id);
  }

  public ASTAddCommand(VctrlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VctrlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=de172be9c7936a2281e82d993acef5fc (do not edit this line) */
