/* Generated By:JJTree: Do not edit this line. ASTBranchCommand.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package duongtran.vctrl.cli.parser;

public
class ASTBranchCommand extends SimpleNode {
  public ASTBranchCommand(int id) {
    super(id);
  }

  public ASTBranchCommand(VctrlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VctrlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=743bd923f5d67494c6f0ba53fbd5311b (do not edit this line) */
