/* Generated By:JJTree: Do not edit this line. ASTCommitCommand.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package duongtran.vctrl.cli.parser;

public
class ASTCommitCommand extends SimpleNode {
  public ASTCommitCommand(int id) {
    super(id);
  }

  public ASTCommitCommand(VctrlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VctrlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=037b2f151e1818b8d2ab26f609dc0588 (do not edit this line) */
