/* Generated By:JJTree: Do not edit this line. ASTCheckoutCommand.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package duongtran.vctrl.cli.parser;

public
class ASTCheckoutCommand extends SimpleNode {
  public ASTCheckoutCommand(int id) {
    super(id);
  }

  public ASTCheckoutCommand(VctrlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VctrlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0a2d8ee6aaa37bd754af3b9971ecf378 (do not edit this line) */
