/* Generated By:JJTree: Do not edit this line. ASTInitCommand.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package duongtran.vctrl.cli.parser;

public
class ASTInitCommand extends SimpleNode {
  public ASTInitCommand(int id) {
    super(id);
  }

  public ASTInitCommand(VctrlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VctrlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cc6bf643340586ce1fb9503b558b4774 (do not edit this line) */
