/* Generated By:JJTree: Do not edit this line. ASTStatusCommand.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package duongtran.vctrl.cli.parser;

public
class ASTStatusCommand extends SimpleNode {
  public ASTStatusCommand(int id) {
    super(id);
  }

  public ASTStatusCommand(VctrlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VctrlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=48997afed247a5fe92bec5ff0f88fc56 (do not edit this line) */
