/* Generated By:JavaCC: Do not edit this line. VctrlParserVisitor.java Version 7.0.12 */
package duongtran.vctrl.cli.parser;

public interface VctrlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCommand node, Object data);
  public Object visit(ASTInitCommand node, Object data);
  public Object visit(ASTAddCommand node, Object data);
}
/* JavaCC - OriginalChecksum=b4b8cef598e0a29e4e11eb2c5d161a7f (do not edit this line) */
