/* Generated By:JavaCC: Do not edit this line. VctrlParserTreeConstants.java Version 7.0.13 */
package duongtran.vctrl.cli.parser;

public interface VctrlParserTreeConstants
{
  public int JJTCOMMAND = 0;
  public int JJTINITCOMMAND = 1;
  public int JJTADDCOMMAND = 2;
  public int JJTCOMMITCOMMAND = 3;
  public int JJTSTATUSCOMMAND = 4;
  public int JJTBRANCHCOMMAND = 5;
  public int JJTCHECKOUTCOMMAND = 6;
  public int JJTLOGCOMMAND = 7;


  public String[] jjtNodeName = {
    "Command",
    "InitCommand",
    "AddCommand",
    "CommitCommand",
    "StatusCommand",
    "BranchCommand",
    "CheckoutCommand",
    "LogCommand",
  };
}
/* JavaCC - OriginalChecksum=c9eeb1e61dfecf08ea6d89164bf01f4a (do not edit this line) */
