/* Generated By:JJTree&JavaCC: Do not edit this line. VctrlParserConstants.java */
package duongtran.vctrl.cli.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VctrlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_INIT = 5;
  /** RegularExpression Id. */
  int K_STATUS = 6;
  /** RegularExpression Id. */
  int K_ADD = 7;
  /** RegularExpression Id. */
  int K_COMMIT = 8;
  /** RegularExpression Id. */
  int K_LOG = 9;
  /** RegularExpression Id. */
  int K_BRANCH = 10;
  /** RegularExpression Id. */
  int K_CHECKOUT = 11;
  /** RegularExpression Id. */
  int K_MERGE = 12;
  /** RegularExpression Id. */
  int K_DIFF = 13;
  /** RegularExpression Id. */
  int K_M = 14;
  /** RegularExpression Id. */
  int K_D = 15;
  /** RegularExpression Id. */
  int K_B = 16;
  /** RegularExpression Id. */
  int ONELINE = 17;
  /** RegularExpression Id. */
  int GRAPH = 18;
  /** RegularExpression Id. */
  int PRETTY = 19;
  /** RegularExpression Id. */
  int FORMAT = 20;
  /** RegularExpression Id. */
  int CARET = 21;
  /** RegularExpression Id. */
  int DOTDOT = 22;
  /** RegularExpression Id. */
  int EQUAL = 23;
  /** RegularExpression Id. */
  int NO_FF = 24;
  /** RegularExpression Id. */
  int SQUASH = 25;
  /** RegularExpression Id. */
  int CACHED = 26;
  /** RegularExpression Id. */
  int QUOTED = 27;
  /** RegularExpression Id. */
  int ATOM = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"init\"",
    "\"status\"",
    "\"add\"",
    "\"commit\"",
    "\"log\"",
    "\"branch\"",
    "\"checkout\"",
    "\"merge\"",
    "\"diff\"",
    "\"-m\"",
    "\"-d\"",
    "\"-b\"",
    "\"--oneline\"",
    "\"--graph\"",
    "\"--pretty\"",
    "\"--format\"",
    "\"^\"",
    "\"..\"",
    "\"=\"",
    "\"--no-ff\"",
    "\"--squash\"",
    "\"--cached\"",
    "<QUOTED>",
    "<ATOM>",
  };

}
