/* Generated By:JavaCC: Do not edit this line. VctrlParserVisitor.java Version 7.0.13 */
package duongtran.vctrl.cli.parser;

public interface VctrlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCommand node, Object data);
  public Object visit(ASTInitCommand node, Object data);
  public Object visit(ASTAddCommand node, Object data);
}
/* JavaCC - OriginalChecksum=d70096901bb326db17737337905a96f6 (do not edit this line) */
