/* Generated By:JavaCC: Do not edit this line. VctrlParserTreeConstants.java Version 7.0.12 */
package duongtran.vctrl.cli.parser;

public interface VctrlParserTreeConstants
{
  public int JJTCOMMAND = 0;
  public int JJTINITCOMMAND = 1;
  public int JJTADDCOMMAND = 2;
  public int JJTCOMMITCOMMAND = 3;


  public String[] jjtNodeName = {
    "Command",
    "InitCommand",
    "AddCommand",
    "CommitCommand",
  };
}
/* JavaCC - OriginalChecksum=e341a74c425438a5688e6982de3eca4f (do not edit this line) */
