/* Generated By:JavaCC: Do not edit this line. VctrlParserVisitor.java Version 7.0.12 */
package duongtran.vctrl.cli.parser;

public interface VctrlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCommand node, Object data);
  public Object visit(ASTInitCommand node, Object data);
  public Object visit(ASTAddCommand node, Object data);
  public Object visit(ASTCommitCommand node, Object data);
  public Object visit(ASTStatusCommand node, Object data);
  public Object visit(ASTBranchCommand node, Object data);
  public Object visit(ASTCheckoutCommand node, Object data);
  public Object visit(ASTLogCommand node, Object data);
  public Object visit(ASTMergeCommand node, Object data);
  public Object visit(ASTDiffCommand node, Object data);
}
/* JavaCC - OriginalChecksum=45fcdd912c09531b78cee9664f38fd31 (do not edit this line) */
