/* Generated By:JJTree&JavaCC: Do not edit this line. VctrlParserConstants.java */
package duongtran.vctrl.cli.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VctrlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_INIT = 5;
  /** RegularExpression Id. */
  int K_STATUS = 6;
  /** RegularExpression Id. */
  int K_ADD = 7;
  /** RegularExpression Id. */
  int K_COMMIT = 8;
  /** RegularExpression Id. */
  int K_LOG = 9;
  /** RegularExpression Id. */
  int K_BRANCH = 10;
  /** RegularExpression Id. */
  int K_CHECKOUT = 11;
  /** RegularExpression Id. */
  int K_MERGE = 12;
  /** RegularExpression Id. */
  int K_M = 13;
  /** RegularExpression Id. */
  int K_D = 14;
  /** RegularExpression Id. */
  int K_B = 15;
  /** RegularExpression Id. */
  int ONELINE = 16;
  /** RegularExpression Id. */
  int PRETTY = 17;
  /** RegularExpression Id. */
  int FORMAT = 18;
  /** RegularExpression Id. */
  int GRAPH = 19;
  /** RegularExpression Id. */
  int CARET = 20;
  /** RegularExpression Id. */
  int DOTDOT = 21;
  /** RegularExpression Id. */
  int EQUAL = 22;
  /** RegularExpression Id. */
  int STRING_LITERAL = 23;
  /** RegularExpression Id. */
  int FORMAT_STR = 24;
  /** RegularExpression Id. */
  int PATH = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"init\"",
    "\"status\"",
    "\"add\"",
    "\"commit\"",
    "\"log\"",
    "\"branch\"",
    "\"checkout\"",
    "\"merge\"",
    "\"-m\"",
    "\"-d\"",
    "\"-b\"",
    "\"--oneline\"",
    "\"--pretty\"",
    "\"--format\"",
    "\"--graph\"",
    "\"^\"",
    "\"..\"",
    "\"=\"",
    "<STRING_LITERAL>",
    "<FORMAT_STR>",
    "<PATH>",
  };

}
