/* Generated By:JavaCC: Do not edit this line. VctrlParserDefaultVisitor.java Version 7.0.12 */
package duongtran.vctrl.cli.parser;

public class VctrlParserDefaultVisitor implements VctrlParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInitCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAddCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCommitCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatusCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBranchCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCheckoutCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLogCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMergeCommand node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=e062963e41d57c1f14b3a131c322040f (do not edit this line) */
