/* VctrlParser.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. VctrlParser.java */
package duongtran.vctrl.cli.parser;

import duongtran.vctrl.cli.visitor.args.BranchCommandData;
import duongtran.vctrl.cli.visitor.args.CheckoutCommandData;
import duongtran.vctrl.cli.visitor.args.LogCommandData;

@SuppressWarnings("all")
public class VctrlParser/*@bgen(jjtree)*/implements VctrlParserTreeConstants, VctrlParserConstants {/*@bgen(jjtree)*/
  protected JJTVctrlParserState jjtree = new JJTVctrlParserState();

/* ====== ENTRY ====== */
  final public ASTCommand command() throws ParseException {/*@bgen(jjtree) Command */
  ASTCommand jjtn000 = new ASTCommand(JJTCOMMAND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_INIT:{
        init_cmd();
        break;
        }
      case K_ADD:{
        add_cmd();
        break;
        }
      case K_COMMIT:{
        commit_cmd();
        break;
        }
      case K_STATUS:{
        status_cmd();
        break;
        }
      case K_BRANCH:{
        branch_cmd();
        break;
        }
      case K_CHECKOUT:{
        checkout_cmd();
        break;
        }
      case K_LOG:{
        log_cmd();
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/* ====== COMMANDS ====== */
  final public 
void init_cmd() throws ParseException {/*@bgen(jjtree) InitCommand */
    ASTInitCommand jjtn000 = new ASTInitCommand(JJTINITCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token path = null;
    try {
      jj_consume_token(K_INIT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PATH:{
        path = jj_consume_token(PATH);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
if (path != null) {
            jjtn000.jjtSetValue(path.image);
        }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void add_cmd() throws ParseException {/*@bgen(jjtree) AddCommand */
    ASTAddCommand jjtn000 = new ASTAddCommand(JJTADDCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token path;
    try {
      jj_consume_token(K_ADD);
      path = jj_consume_token(PATH);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.jjtSetValue(path.image);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void commit_cmd() throws ParseException {/*@bgen(jjtree) CommitCommand */
    ASTCommitCommand jjtn000 = new ASTCommitCommand(JJTCOMMITCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token msg;
    try {
      jj_consume_token(K_COMMIT);
      jj_consume_token(K_M);
      msg = jj_consume_token(STRING_LITERAL);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
String m = msg.image;
        if (m.startsWith("\"") && m.endsWith("\"")) {
            m = m.substring(1, m.length() - 1);
        }
        jjtn000.jjtSetValue(m);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void status_cmd() throws ParseException {/*@bgen(jjtree) StatusCommand */
  ASTStatusCommand jjtn000 = new ASTStatusCommand(JJTSTATUSCOMMAND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(K_STATUS);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void branch_cmd() throws ParseException {/*@bgen(jjtree) BranchCommand */
    ASTBranchCommand jjtn000 = new ASTBranchCommand(JJTBRANCHCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token name = null; // branch's name
    boolean delete = false;
    try {
      jj_consume_token(K_BRANCH);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_D:
      case PATH:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case K_D:{
          jj_consume_token(K_D);
delete = true;
          name = jj_consume_token(PATH);
          break;
          }
        case PATH:{
          name = jj_consume_token(PATH);
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
BranchCommandData data = new BranchCommandData();
        data.name = name != null ? name.image : null;
        data.delete = delete;
        jjtn000.jjtSetValue(data);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void checkout_cmd() throws ParseException {/*@bgen(jjtree) CheckoutCommand */
    ASTCheckoutCommand jjtn000 = new ASTCheckoutCommand(JJTCHECKOUTCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token name = null; // branch name
    boolean create = false;
    try {
      jj_consume_token(K_CHECKOUT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_B:
      case PATH:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case K_B:{
          jj_consume_token(K_B);
create = true;
          name = jj_consume_token(PATH);
          break;
          }
        case PATH:{
          name = jj_consume_token(PATH);
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
CheckoutCommandData data = new CheckoutCommandData();
        data.name = name.image;
        data.create = create;
        jjtn000.jjtSetValue(data);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void log_cmd() throws ParseException {/*@bgen(jjtree) LogCommand */
    ASTLogCommand jjtn000 = new ASTLogCommand(JJTLOGCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token opt = null;
    Token fmt = null;
    java.util.List branches = new java.util.ArrayList();
    Token branch;
    try {
      jj_consume_token(K_LOG);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ONELINE:
      case PRETTY:
      case FORMAT:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ONELINE:{
          opt = jj_consume_token(ONELINE);
          break;
          }
        case PRETTY:
        case FORMAT:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PRETTY:{
            jj_consume_token(PRETTY);
            break;
            }
          case FORMAT:{
            jj_consume_token(FORMAT);
            break;
            }
          default:
            jj_la1[6] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          jj_consume_token(EQUAL);
          fmt = jj_consume_token(FORMAT_STR);
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PATH:{
          ;
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          break label_1;
        }
        branch = jj_consume_token(PATH);
branches.add(branch.image);
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
LogCommandData data = new LogCommandData();

        // OneLine format
        if (opt != null && opt.image.equals("--oneline")) {
            data.oneline = true;
        }

        // Data format
        data.format = null;
        if (fmt != null) {
            String m = fmt.image;
            if (m.startsWith("\"") && m.endsWith("\"")) {
                m = m.substring(1, m.length() - 1);
            }
            data.format = m;
        }

        // List of branches
        data.branches = branches;

        jjtn000.jjtSetValue(data);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  /** Generated Token Manager. */
  public VctrlParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[10];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xfe0,0x200000,0x204000,0x204000,0x208000,0x208000,0x60000,0x70000,0x70000,0x200000,};
	}

  /** Constructor with InputStream. */
  public VctrlParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public VctrlParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e.getMessage()); }
	 token_source = new VctrlParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e.getMessage()); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public VctrlParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new VctrlParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new VctrlParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public VctrlParser(VctrlParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(VctrlParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[23];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 10; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 23; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = (int[])jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
