/* VctrlParser.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. VctrlParser.java */
package duongtran.vctrl.cli.parser;

import duongtran.vctrl.cli.visitor.args.BranchCommandData;
import duongtran.vctrl.cli.visitor.args.CheckoutCommandData;
import duongtran.vctrl.cli.visitor.args.LogCommandData;
import duongtran.vctrl.cli.visitor.args.LogRevisionSpec;

@SuppressWarnings("all")
public class VctrlParser/*@bgen(jjtree)*/implements VctrlParserTreeConstants, VctrlParserConstants {/*@bgen(jjtree)*/
  protected JJTVctrlParserState jjtree = new JJTVctrlParserState();
    private static String stripQuotes(String s) {
        if (s == null || s.length() < 2) {
            return s;
        }
        if ((s.startsWith("\"") && s.endsWith("\""))
         || (s.startsWith("'") && s.endsWith("'"))) {
            return s.substring(1, s.length() - 1);
        }
        return s;
    }

/* ====== ENTRY ====== */
  final public ASTCommand command() throws ParseException {/*@bgen(jjtree) Command */
  ASTCommand jjtn000 = new ASTCommand(JJTCOMMAND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_INIT:{
        init_cmd();
        break;
        }
      case K_ADD:{
        add_cmd();
        break;
        }
      case K_COMMIT:{
        commit_cmd();
        break;
        }
      case K_STATUS:{
        status_cmd();
        break;
        }
      case K_BRANCH:{
        branch_cmd();
        break;
        }
      case K_CHECKOUT:{
        checkout_cmd();
        break;
        }
      case K_LOG:{
        log_cmd();
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/* ====== COMMANDS ====== */
  final public 
void init_cmd() throws ParseException {/*@bgen(jjtree) InitCommand */
    ASTInitCommand jjtn000 = new ASTInitCommand(JJTINITCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token path = null;
    try {
      jj_consume_token(K_INIT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PATH:{
        path = jj_consume_token(PATH);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
if (path != null) {
            jjtn000.jjtSetValue(path.image);
        }
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void add_cmd() throws ParseException {/*@bgen(jjtree) AddCommand */
    ASTAddCommand jjtn000 = new ASTAddCommand(JJTADDCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token path;
    try {
      jj_consume_token(K_ADD);
      path = jj_consume_token(PATH);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
jjtn000.jjtSetValue(path.image);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void commit_cmd() throws ParseException {/*@bgen(jjtree) CommitCommand */
    ASTCommitCommand jjtn000 = new ASTCommitCommand(JJTCOMMITCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token msg;
    try {
      jj_consume_token(K_COMMIT);
      jj_consume_token(K_M);
      msg = jj_consume_token(STRING_LITERAL);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
String m = msg.image;
        if (m.startsWith("\"") && m.endsWith("\"")) {
            m = m.substring(1, m.length() - 1);
        }
        jjtn000.jjtSetValue(m);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void status_cmd() throws ParseException {/*@bgen(jjtree) StatusCommand */
  ASTStatusCommand jjtn000 = new ASTStatusCommand(JJTSTATUSCOMMAND);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(K_STATUS);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void branch_cmd() throws ParseException {/*@bgen(jjtree) BranchCommand */
    ASTBranchCommand jjtn000 = new ASTBranchCommand(JJTBRANCHCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token name = null; // branch's name
    boolean delete = false;
    try {
      jj_consume_token(K_BRANCH);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_D:
      case PATH:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case K_D:{
          jj_consume_token(K_D);
delete = true;
          name = jj_consume_token(PATH);
          break;
          }
        case PATH:{
          name = jj_consume_token(PATH);
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
BranchCommandData data = new BranchCommandData();
        data.name = name != null ? name.image : null;
        data.delete = delete;
        jjtn000.jjtSetValue(data);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void checkout_cmd() throws ParseException {/*@bgen(jjtree) CheckoutCommand */
    ASTCheckoutCommand jjtn000 = new ASTCheckoutCommand(JJTCHECKOUTCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);Token name = null; // branch name
    boolean create = false;
    try {
      jj_consume_token(K_CHECKOUT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_B:
      case PATH:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case K_B:{
          jj_consume_token(K_B);
create = true;
          name = jj_consume_token(PATH);
          break;
          }
        case PATH:{
          name = jj_consume_token(PATH);
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        ;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
CheckoutCommandData data = new CheckoutCommandData();
        data.name = name.image;
        data.create = create;
        jjtn000.jjtSetValue(data);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  final public void log_cmd() throws ParseException {/*@bgen(jjtree) LogCommand */
    ASTLogCommand jjtn000 = new ASTLogCommand(JJTLOGCOMMAND);
    boolean jjtc000 = true;
    jjtree.openNodeScope(jjtn000);
      LogRevisionSpec revSpec = new LogRevisionSpec();

    boolean oneline = false;
    boolean graph = false;
    String format = null;

    Token fmt = null;
    Token t1, t2;
    try {
      jj_consume_token(K_LOG);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ONELINE:
        case PRETTY:
        case FORMAT:
        case GRAPH:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_1;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ONELINE:{
          jj_consume_token(ONELINE);
oneline = true;
          break;
          }
        case GRAPH:{
          jj_consume_token(GRAPH);
graph = true;
          break;
          }
        case PRETTY:
        case FORMAT:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PRETTY:{
            jj_consume_token(PRETTY);
            break;
            }
          case FORMAT:{
            jj_consume_token(FORMAT);
            break;
            }
          default:
            jj_la1[7] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          jj_consume_token(EQUAL);
          fmt = jj_consume_token(FORMAT_STR);
format = stripQuotes(fmt.image);
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CARET:
        case PATH:{
          ;
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          break label_2;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CARET:{
          jj_consume_token(CARET);
          t1 = jj_consume_token(PATH);
revSpec.exclude.add(t1.image);
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          if (jj_2_1(2147483647)) {
            /* A..B */
                    t1 = jj_consume_token(PATH);
            jj_consume_token(DOTDOT);
            t2 = jj_consume_token(PATH);
revSpec.exclude.add(t1.image);
            revSpec.include.add(t2.image);
          } else if (jj_2_2(2147483647)) {
            /* normal branch */
                    t1 = jj_consume_token(PATH);
revSpec.include.add(t1.image);
          } else {
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
LogCommandData data = new LogCommandData();
        data.oneline = oneline;
        data.graph = graph;
        data.format = format;
        data.revSpec = revSpec;

        jjtn000.jjtSetValue(data);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_3_1()
 {
    if (jj_scan_token(PATH)) return true;
    if (jj_scan_token(DOTDOT)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_scan_token(PATH)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public VctrlParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[11];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xfe0,0x2000000,0x2004000,0x2004000,0x2008000,0x2008000,0xf0000,0x60000,0xf0000,0x2100000,0x100000,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public VctrlParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public VctrlParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e.getMessage()); }
	 token_source = new VctrlParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e.getMessage()); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public VctrlParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new VctrlParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new VctrlParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public VctrlParser(VctrlParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(VctrlParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 11; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
		 int[] oldentry = (int[])(it.next());
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[26];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 11; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 26; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = (int[])jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 2; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
