/* Generated By:JavaCC: Do not edit this line. VctrlParserTreeConstants.java Version 7.0.13 */
package duongtran.vctrl.cli.parser;

public interface VctrlParserTreeConstants
{
  public int JJTCOMMAND = 0;
  public int JJTINITCOMMAND = 1;
  public int JJTADDCOMMAND = 2;


  public String[] jjtNodeName = {
    "Command",
    "InitCommand",
    "AddCommand",
  };
}
/* JavaCC - OriginalChecksum=4180ac239df02b256fc63feb773d79c0 (do not edit this line) */
