/* Generated By:JavaCC: Do not edit this line. VctrlParserDefaultVisitor.java Version 7.0.13 */
package duongtran.vctrl.cli.parser;

public class VctrlParserDefaultVisitor implements VctrlParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInitCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAddCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCommitCommand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatusCommand node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=6d48bc33edbc5b307efa03a3f1a1cc4c (do not edit this line) */
